Increase robustness of SSL renewing
The playground had an error renewing:

```
Error -> One or more domains had a problem:
error: 0 :: POST :: https://acme-v02.api.letsencrypt.org/acme/finalize/514094497/249375107307 :: urn:ietf:params:acme:error:rateLimited :: Service busy; retry later., url:
```

Our renew timer runs once a week at midnight UTC, and my guess is that
lots of other servers across the world are doing the same thing
causing temporary overloads. These changes are intended to help spread
out the load a bit and retry when an error happens anyway.